//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSPModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KDSPEntities : DbContext
    {
        public KDSPEntities()
            : base("name=KDSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasterSheet> MasterSheets { get; set; }
        public virtual DbSet<PatientAppointment> PatientAppointments { get; set; }
        public virtual DbSet<PatientPaymentHistory> PatientPaymentHistories { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Therapist> Therapists { get; set; }
        public virtual DbSet<TherapistSchedule> TherapistSchedules { get; set; }
        public virtual DbSet<TherapyCharge> TherapyCharges { get; set; }
        public virtual DbSet<WaitingList> WaitingLists { get; set; }
        public virtual DbSet<HolidayCalendar> HolidayCalendars { get; set; }
        public virtual DbSet<v_PatientWaitingList> v_PatientWaitingList { get; set; }
    
        public virtual int usp_GenerateTherapistSchedule(Nullable<int> therapistId)
        {
            var therapistIdParameter = therapistId.HasValue ?
                new ObjectParameter("TherapistId", therapistId) :
                new ObjectParameter("TherapistId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GenerateTherapistSchedule", therapistIdParameter);
        }
    }
}
