//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSPModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSheet
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> TherapistId { get; set; }
        public Nullable<int> PatientAppointmentId { get; set; }
        public Nullable<int> PatientPaymentHistoryId { get; set; }
        public string TherapyStatus { get; set; }
        public string FirstCancellationOfMonth { get; set; }
        public string Inform24HrPrior { get; set; }
    }
}
