//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSPModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public string PatientFullName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FatherFullName { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ContactNo { get; set; }
        public string Remarks { get; set; }
        public string TherapyDept { get; set; }
        public string Status { get; set; }
        public string VisitFrequency { get; set; }
        public string PatientRegNo { get; set; }
    }
}
