//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSPModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAppointment
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> TherapistId { get; set; }
        public Nullable<int> SessionNumber { get; set; }
        public Nullable<int> TherapistScheduleId { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime AppointmentDate { get; set; }
    }
}
