//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDSPModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapist
    {
        public int Id { get; set; }
        public string TherapistFullName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.TimeSpan> ShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> ShiftEndTime { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClinicStartDate { get; set; }
        public Nullable<System.DateTime> ClinicEndDate { get; set; }
        public string IsSatWorking { get; set; }
        public string IsSunWorking { get; set; }
        public string IsMonWorking { get; set; }
        public string IsTueWorking { get; set; }
        public string IsWedWorking { get; set; }
        public string IsThuWorking { get; set; }
        public string IsFriWorking { get; set; }
        public Nullable<System.TimeSpan> BreakStartTime { get; set; }
        public Nullable<System.TimeSpan> BreakEndTime { get; set; }
        public string OTTherapist { get; set; }
        public string PTTherapist { get; set; }
        public string StTherapist { get; set; }
        public string TherapistRegNo { get; set; }
    }
}
